<?php
/**
 * Image resolution, sideloading, and IN-CONTENT image placement.
 *
 * ============================================================================
 * RESOLUTION ORDER (cheapest first)
 * ============================================================================
 *   1. Already resolved for this job  -> $0, and prevents double-billing on retry
 *   2. Local media library match      -> $0
 *   3. AI generation (if enabled)     -> $0.003+ per image
 *
 * ============================================================================
 * INLINE IMAGES ARE ALWAYS LIBRARY-SOURCED
 * ============================================================================
 * A 3-image article generated by AI costs 3x the featured-image price, which for a
 * 100-page import is the single largest avoidable line on the bill. In-content
 * images therefore come EXCLUSIVELY from the existing media library — matched by
 * the surrounding H2 text, so the picture is topically relevant to the section it
 * sits in. If the library cannot match, the section simply has no image, which is
 * always better than a surprise invoice.
 *
 * Because these sites have already published hundreds of pages, the library is
 * usually rich enough that this is a quality win as well as a cost win: real
 * on-brand photography beats generic AI renders.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

class WAB_Image_Handler {

    /**
     * Resolve the featured image for a job.
     *
     * @param object $job     Job row (carries attachment_id for retry reuse).
     * @param object $row     Import row.
     * @param array  $content Generated payload.
     * @return int|WP_Error Attachment ID.
     */
    public static function resolve_featured( $job, $row, array $content ) {

        // ---- 1. Already paid for. -------------------------------------
        // THE anti-double-billing mechanism. v1 generated the image before
        // inserting the post and persisted nothing between, so every retry and every
        // duplicate claim bought another image — up to 5-10 per post.
        if ( ! empty( $job->attachment_id ) ) {
            $existing = (int) $job->attachment_id;
            if ( get_post_type( $existing ) === 'attachment' ) {
                WAB_Logger::info( sprintf( 'Job %s reusing attachment %d (no new cost).', $job->job_id, $existing ) );
                return $existing;
            }
        }

        $source = get_option( 'wab_image_source', 'library_then_ai' );
        if ( $source === 'none' ) {
            return new WP_Error( 'wab_image_disabled', __( 'Images disabled for this import.', 'wonder-ai-builder' ) );
        }

        // ---- 2. Local library. ---------------------------------------
        if ( in_array( $source, array( 'library_only', 'library_then_ai' ), true ) ) {
            $match = WAB_Image_Library::find_best( $row, $content, array(
                'min_width' => (int) get_option( 'wab_image_min_width', 600 ),
            ) );

            if ( ! is_wp_error( $match ) ) {
                WAB_Image_Library::mark_used( $match );
                WAB_Queue::record_attachment( $job->job_id, $match );
                WAB_Logger::info( sprintf( 'Job %s matched local image %d ($0.00).', $job->job_id, $match ) );
                return (int) $match;
            }

            if ( $source === 'library_only' ) {
                // Permanent: no amount of retrying will conjure a matching image.
                return new WP_Error( 'wab_image_disabled', $match->get_error_message() );
            }
        }

        // ---- 3. AI generation. ---------------------------------------
        $provider = WAB_Provider_Registry::image();
        if ( ! $provider->is_configured() ) {
            return new WP_Error( 'wab_no_key', __( 'Image provider is not configured.', 'wonder-ai-builder' ) );
        }

        $prompt = self::build_image_prompt( $row, $content );
        $model  = WAB_Provider_Registry::image_model( $provider );

        $result = $provider->generate( $prompt, array(
            'model'  => $model,
            'width'  => (int) get_option( 'wab_image_width', 1280 ),
            'height' => (int) get_option( 'wab_image_height', 720 ),
        ) );

        if ( is_wp_error( $result ) ) return $result;

        // Record spend BEFORE sideloading. The money is already gone at this point;
        // a sideload failure must not hide it.
        $cost = (float) ( $result['cost'] ?? 0 );
        if ( $cost > 0 ) {
            WAB_Cost_Guard::record( $cost, 'image' );
            WAB_Queue::record_cost( $job->job_id, $cost );
        }

        $title = $content['title'] ?? ( $row->title ?? '' );
        $alt   = self::build_alt_text( $row, $content );

        $attachment_id = ( ( $result['source'] ?? '' ) === 'base64' )
            ? self::sideload_base64( $result['data'], $title, $alt, $result['mime'] ?? 'image/png' )
            : self::sideload_url( $result['data'], $title, $alt );

        if ( is_wp_error( $attachment_id ) ) return $attachment_id;

        WAB_Queue::record_attachment( $job->job_id, $attachment_id );

        return (int) $attachment_id;
    }

    /**
     * Insert library images into the generated body at section boundaries.
     *
     * Matched against each H2's own text so the image suits its section. Never
     * generates — always free.
     *
     * @return string HTML with <figure> blocks inserted.
     */
    public static function inject_inline_images( $html, $row, array $content ) {
        $max = (int) get_option( 'wab_inline_images', 2 );
        if ( $max <= 0 || trim( (string) $html ) === '' ) return $html;

        // Split on H2 boundaries, keeping the delimiters.
        $parts = preg_split( '#(<h2\b[^>]*>.*?</h2>)#is', $html, -1, PREG_SPLIT_DELIM_CAPTURE );
        if ( ! is_array( $parts ) || count( $parts ) < 3 ) return $html;

        $used     = array();
        $inserted = 0;
        $out      = '';

        // Exclude the featured image so the same picture is not shown twice.
        if ( ! empty( $content['_featured_id'] ) ) {
            $used[] = (int) $content['_featured_id'];
        }

        foreach ( $parts as $part ) {
            $out .= $part;

            if ( $inserted >= $max ) continue;
            if ( ! preg_match( '#^<h2\b#i', $part ) ) continue;

            // Skip the very first section: an image immediately under the opening
            // H2 competes with the featured image for attention.
            if ( $inserted === 0 && strpos( $out, '</h2>' ) === strlen( $out ) - 5 && substr_count( $out, '<h2' ) === 1 ) {
                continue;
            }

            $heading = WAB_Content_Sanitizer::clean_text( $part, 120 );
            if ( $heading === '' ) continue;

            // Match on the heading plus the row's own topical fields.
            $probe = (object) array(
                'topic'    => $heading,
                'services' => $row->services ?? '',
                'location' => $row->location ?? '',
                'keywords' => $row->keywords ?? '',
                'category' => $row->category ?? '',
            );

            $match = WAB_Image_Library::find_best( $probe, array(), array(
                'exclude_ids' => $used,
                'min_width'   => 480,
            ) );

            if ( is_wp_error( $match ) ) continue;

            $out .= self::figure_html( (int) $match, $heading );
            WAB_Image_Library::mark_used( $match );

            $used[] = (int) $match;
            $inserted++;
        }

        if ( $inserted > 0 ) {
            WAB_Logger::info( sprintf( 'Inserted %d inline library image(s) at $0.00.', $inserted ) );
        }

        return $out;
    }

    /**
     * Responsive, lazy-loaded figure. Uses WordPress's own srcset generation so
     * the theme's image sizes are respected.
     */
    private static function figure_html( $attachment_id, $context_label ) {
        $alt = (string) get_post_meta( $attachment_id, '_wp_attachment_image_alt', true );
        if ( $alt === '' ) $alt = $context_label;

        $img = wp_get_attachment_image( $attachment_id, 'large', false, array(
            'alt'      => esc_attr( $alt ),
            'loading'  => 'lazy',
            'decoding' => 'async',
            'class'    => 'wab-inline-image',
        ) );

        if ( ! $img ) return '';

        $caption = wp_get_attachment_caption( $attachment_id );

        $html  = "\n<figure class=\"wp-block-image size-large wab-inline-figure\">" . $img;
        if ( $caption ) {
            $html .= '<figcaption class="wp-element-caption">' . esc_html( $caption ) . '</figcaption>';
        }
        $html .= "</figure>\n";

        return $html;
    }

    // ---------------------------------------------------------------
    // Sideloading
    // ---------------------------------------------------------------

    /**
     * Download a remote image into the media library.
     *
     * SSRF-guarded, unlike v1, which passed $_POST['image_url'] through
     * esc_url_raw() — a syntax check, not a safety check — and let any Author-level
     * user make the server fetch cloud IAM metadata or probe internal services.
     */
    public static function sideload_url( $url, $title = '', $alt = '' ) {
        $valid = WAB_Security::validate_outbound_url( $url );
        if ( is_wp_error( $valid ) ) return $valid;

        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/media.php';
        require_once ABSPATH . 'wp-admin/includes/image.php';

        $tmp = download_url( $url, 60 );
        if ( is_wp_error( $tmp ) ) return $tmp;

        // Confirm it is genuinely an image before it enters the library.
        $check = wp_getimagesize( $tmp );
        if ( empty( $check ) ) {
            @unlink( $tmp );
            return new WP_Error( 'wab_not_an_image', __( 'Downloaded file is not a valid image.', 'wonder-ai-builder' ) );
        }

        return self::finish_sideload( $tmp, $title, $alt );
    }

    public static function sideload_base64( $b64, $title = '', $alt = '', $mime = 'image/png' ) {
        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/media.php';
        require_once ABSPATH . 'wp-admin/includes/image.php';

        $binary = base64_decode( (string) $b64, true );
        if ( $binary === false || $binary === '' ) {
            return new WP_Error( 'wab_bad_base64', __( 'Invalid base64 image payload.', 'wonder-ai-builder' ) );
        }

        $ext = ( strpos( $mime, 'png' ) !== false ) ? 'png' : 'jpg';
        $tmp = wp_tempnam( 'wab-image.' . $ext );
        if ( ! $tmp ) {
            return new WP_Error( 'wab_tmp_failed', __( 'Could not create a temporary file.', 'wonder-ai-builder' ) );
        }

        file_put_contents( $tmp, $binary );
        unset( $binary ); // Free the payload promptly; these can be multi-MB.

        if ( empty( wp_getimagesize( $tmp ) ) ) {
            @unlink( $tmp );
            return new WP_Error( 'wab_not_an_image', __( 'Decoded payload is not a valid image.', 'wonder-ai-builder' ) );
        }

        return self::finish_sideload( $tmp, $title, $alt );
    }

    private static function finish_sideload( $tmp, $title, $alt ) {
        $optimized = self::optimize( $tmp );

        $type = wp_check_filetype( $optimized );
        $ext  = $type['ext'] ?: 'webp';
        $mime = $type['type'] ?: 'image/webp';

        $slug     = sanitize_title( $title ) ?: 'wab-image-' . gmdate( 'YmdHis' );
        $filename = substr( $slug, 0, 80 ) . '.' . $ext;

        $file_array = array(
            'name'     => $filename,
            'tmp_name' => $optimized,
            'type'     => $mime,
            'error'    => 0,
            'size'     => (int) @filesize( $optimized ),
        );

        $attachment_id = media_handle_sideload( $file_array, 0, $title );

        // media_handle_sideload moves the file on success; clean up on failure.
        if ( is_wp_error( $attachment_id ) ) {
            if ( file_exists( $optimized ) ) @unlink( $optimized );
            if ( $tmp !== $optimized && file_exists( $tmp ) ) @unlink( $tmp );
            WAB_Logger::error( 'Sideload failed: ' . $attachment_id->get_error_message() );
            return $attachment_id;
        }

        if ( $tmp !== $optimized && file_exists( $tmp ) ) @unlink( $tmp );

        if ( $alt !== '' ) {
            update_post_meta( $attachment_id, '_wp_attachment_image_alt', WAB_Content_Sanitizer::clean_text( $alt, 125 ) );
        }

        // Tag provenance so these are findable and so the library matcher can
        // later prefer or avoid AI-generated stock.
        update_post_meta( $attachment_id, '_wab_generated', 1 );

        return (int) $attachment_id;
    }

    /**
     * Resize and convert to WebP. Typically 25-35% of the original bytes, which
     * matters when 200 sites are each adding hundreds of images.
     */
    private static function optimize( $path ) {
        $max_w = (int) get_option( 'wab_image_width', 1280 );
        $max_h = (int) get_option( 'wab_image_height', 720 );

        $editor = wp_get_image_editor( $path );
        if ( is_wp_error( $editor ) ) return $path;

        $size = $editor->get_size();
        if ( ! empty( $size['width'] ) && ( $size['width'] > $max_w || $size['height'] > $max_h ) ) {
            $editor->resize( $max_w, $max_h, false );
        }

        $editor->set_quality( (int) get_option( 'wab_image_quality', 82 ) );

        $info = pathinfo( $path );
        $target = $info['dirname'] . '/' . $info['filename'] . '.webp';

        $saved = $editor->save( $target, 'image/webp' );
        if ( is_wp_error( $saved ) || empty( $saved['path'] ) ) {
            return $path; // WebP unsupported on this host; keep the original.
        }

        return $saved['path'];
    }

    // ---------------------------------------------------------------
    // Prompt / alt helpers
    // ---------------------------------------------------------------

    private static function build_image_prompt( $row, array $content ) {
        // Prefer explicit sheet rules; they are the operator's brand direction.
        $rules = isset( $row->image_rules ) ? trim( (string) $row->image_rules ) : '';

        $subject = $content['title']
            ?? ( $row->services ?? $row->topic ?? $row->title ?? '' );

        $location = isset( $row->location ) ? trim( (string) $row->location ) : '';

        $parts = array();
        $parts[] = 'Professional editorial photograph for a web page about ' . wp_strip_all_tags( (string) $subject ) . '.';
        if ( $location !== '' ) $parts[] = 'Setting evokes ' . $location . '.';
        if ( $rules !== '' )    $parts[] = $rules;

        $parts[] = 'Natural lighting, shallow depth of field, realistic. Wide 16:9 composition with clear negative space.';
        // Text rendering in image models is unreliable; forbid it outright.
        $parts[] = 'No text, no words, no letters, no logos, no watermarks, no signage.';

        return implode( ' ', $parts );
    }

    private static function build_alt_text( $row, array $content ) {
        $base = $content['title'] ?? ( $row->title ?? '' );
        $loc  = isset( $row->location ) ? trim( (string) $row->location ) : '';

        $alt = wp_strip_all_tags( (string) $base );
        if ( $loc !== '' && stripos( $alt, $loc ) === false ) {
            $alt .= ' in ' . $loc;
        }

        return WAB_Content_Sanitizer::clean_text( $alt, 125 );
    }
}
